### ISSUE TITLE
Extend blackjack to keep track of a historical average and add it to the wiki

### ISSUE THREAD

**Issue by ghostwriternr** [metakgp/blackjack#10]
Blackjack currently updates the wiki with the latest grades information but doesn't keep track of any of the past grades. It might help to keep a historical average of sorts too.

If not an average (which might not be the best indicator due to changing profs), just a simple list of past grades can also be added to the Wiki.

**Comment by icyflame** [comment]
Every course page could have a section "past semester grade distributions" that will have the same type of graph for all the semesters we can manage. The page would become pretty long, real fast though.

**Comment by Ayushkaushal** [comment]
I am interested in taking up this issue.

**Comment by ghostwriternr** [comment]
Awesome! Let me know if you need help with something.

**Comment by raivivek** [comment]
It is very important that we preserve grade distribution. Alternatively, we can extract the entire grade-distribution and course statistics into `mcmp` or `mfqp` like project. What do you think about it? @icyflame @hargup 

I am thinking something like: search for a course stats --> get stats --> get a hint "looking for papers?" --> point to `mfqp` etc. :P

**Comment by Ayushkaushal** [comment]
@ghostwriternr  @icyflame @raivivek Here is the app: https://appapp123.herokuapp.com/

**Comment by raivivek** [comment]
Thanks @Ayushkaushal. Great start! Let us know if you'd need more input, but I think you are on right track. Basically, get a nicer search page and improved plots. If you have experience with JS, you could also leverage some great plotting libraries from there. But yeah --- whatever works best.
